In [1]:
import pandas as pd                 # 표 형태 데이터를 다루는 라이브러리
import numpy as np                  # 수치 계산용 라이브러리 (RMSE 계산 등에 사용)
import matplotlib.pyplot as plt     # 그래프 시각화 라이브러리

# train_test_split : 데이터를 학습용과 검즈용으로 나누는 함수
from sklearn.model_selection import train_test_split
# 회귀 모델 평가에 사용할 지표들 (MAE, MSE->RMSE, R2)
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
# ColumnTransformer: 컬럼 종류별로 다른 전처리를 적용하는 도구
from sklearn.compose import ColumnTransformer
# Pipeline: 전처리와 모델 학습을 하나의 흐름으로 묶는 도구
from sklearn.pipeline import Pipeline
# OneHotEncoder: 문자형(범주형) 값을 숫자 형태로 바꾸는 도구
from sklearn.preprocessing import OneHotEncoder
# SimpleImputer: 비어 있는 값(결측치)을 정해진 규칙으로 채우는 도구
from sklearn.impute import SimpleImputer

# XGBRegressor: 숫자 값을 예측하는 회귀용 XGBoost 모델
from xgboost import XGBRegressor

In [2]:
# 그래프 모양 설정
plt.style.use("ggplot")

In [3]:
import matplotlib.font_manager as fm
import warnings

plt.rcParams["font.family"] = "Malgun Gothic"
plt.rcParams["axes.unicode_minus"] = False
warnings.filterwarnings("ignore", category=UserWarning)

In [4]:
df = pd.read_csv("jeju_bus.csv")
# df_model = df.copy()

In [5]:
df.head()

,id,date,route_id,vh_id,route_nm,now_latitude,now_longitude,now_station,now_arrive_time,distance,next_station,next_latitude,next_longitude,next_arrive_time
0,0,2019-10-15,405136001,7997025,360-1,33.456267,126.551750,제주대학교입구,06시,266.0,제대마을,33.457724,126.554014,24
1,1,2019-10-15,405136001,7997025,360-1,33.457724,126.554014,제대마을,06시,333.0,제대아파트,33.458783,126.557353,36
2,2,2019-10-15,405136001,7997025,360-1,33.458783,126.557353,제대아파트,06시,415.0,제주대학교,33.459893,126.561624,40
3,3,2019-10-15,405136001,7997025,360-1,33.479705,126.543811,남국원(아라방면),06시,578.0,제주여자중고등학교(아라방면),33.484860,126.542928,42
4,4,2019-10-15,405136001,7997025,360-1,33.485662,126.494923,도호동,07시,374.0,은남동,33.485822,126.490897,64

In [6]:
df.shape

(210457, 14)

In [7]:
df.columns

Index(['id', 'date', 'route_id', 'vh_id', 'route_nm', 'now_latitude',
       'now_longitude', 'now_station', 'now_arrive_time', 'distance',
       'next_station', 'next_latitude', 'next_longitude', 'next_arrive_time'],
      dtype='str')

In [8]:
df.isnull().sum()

id                  0
date                0
route_id            0
vh_id               0
route_nm            0
now_latitude        0
now_longitude       0
now_station         0
now_arrive_time     0
distance            0
next_station        0
next_latitude       0
next_longitude      0
next_arrive_time    0
dtype: int64

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 210457 entries, 0 to 210456
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                210457 non-null  int64
 1   date              210457 non-null  str
 2   route_id          210457 non-null  int64
 3   vh_id             210457 non-null  int64
 4   route_nm          210457 non-null  str
 5   now_latitude      210457 non-null  float64
 6   now_longitude     210457 non-null  float64
 7   now_station       210457 non-null  str
 8   now_arrive_time   210457 non-null  str
 9   distance          210457 non-null  float64
 10  next_station      210457 non-null  str
 11  next_latitude     210457 non-null  float64
 12  next_longitude    210457 non-null  float64
 13  next_arrive_time  210457 non-null  int64
dtypes: float64(5), int64(4), str(5)
memory usage: 22.5 MB

In [10]:
df.describe()

,id,route_id,vh_id,now_latitude,now_longitude,distance,next_latitude,next_longitude,next_arrive_time
count,210457.000000,2.104570e+05,2.104570e+05,210457.000000,210457.000000,210457.000000,210457.000000,210457.000000,210457.000000
mean,105228.000000,4.052491e+08,7.988694e+06,33.434528,126.603451,490.256100,33.434711,126.603687,85.380824
std,60753.847139,9.132404e+04,6.774077e+03,0.102350,0.123961,520.563932,0.102224,0.123838,85.051170
min,0.000000,4.051360e+08,7.983000e+06,33.244382,126.473300,97.000000,33.244382,126.473300,6.000000
25%,52614.000000,4.051365e+08,7.983093e+06,33.325283,126.523900,291.000000,33.325283,126.524550,44.000000
50%,105228.000000,4.053201e+08,7.983431e+06,33.484667,126.551050,384.000000,33.484860,126.551050,66.000000
75%,157842.000000,4.053201e+08,7.997041e+06,33.500197,126.650322,542.000000,33.500228,126.650322,102.000000
max,210456.000000,4.053281e+08,7.997124e+06,33.556167,126.935188,7461.000000,33.556167,126.935188,2996.000000

target_col = df.columns[-1]

target_col

df.columns

required_cols = df.columns[1:-1]

required_cols

data = df.copy()

data

data["date"]

data["date"] = pd.to_datetime(data["date"])

data["date"].dt.year

data["date"].dt.month

data["date"].dt.dayofweek

data["year"] = data["date"].dt.year

data["month"] = data["date"].dt.month

data

data["now_arrive_time"]

data["now_hour"] = data["now_arrive_time"].str.extract(r"(\d+)").astype(float)

data

data["now_hour"]

data.columns

for col in required_cols:
    print(f"col={col}")
    print("="*100)

[col for col in required_cols if col not in ["date", "vh_id"]]

required_cols[:-2]

missing_cols = [col for col in required_cols if col not in required_cols[:-2]]

missing_cols

True + True + False

if missing_cols:
    print("missing cols 는 True!@#$")
else:
    print("missing cols 는 False")

if missing_cols:
    raise ValueError(f"필수 컬럼 누락!! : {missing_cols}")

missing_cols = [col for col in required_cols if col not in data.columns]

if missing_cols:
    print("missing_cols True!!")
else:
    print("missing_cols False..")

data.columns

target_col

if target_col in data.columns:
    print("target_col true")
else:
    print("target_col false")

snack_df = pd.DataFrame({
    "과자명":["초코파이","오예스","고북칩","짱구"]
})

snack_df

#OneHot Encoding 할꺼다(호소중)
categorical_transformer = Pipeline(steps=[("onehot", OneHotEncoder())])

#과자명 컬럼 One Hot Encoding 할꺼다
preprocessor = ColumnTransformer(
    transformers=[("cat", categorical_transformer,["과자명"])]
)

preprocessor.fit_transform(snack_df)

pd.DataFrame(
    preprocessor.fit_transform(snack_df).toarray(),
    columns = preprocessor.get_feature_names_out()
)

X = prepare_features(df_model)

X

In [11]:
# 예측 대상(정답) 컬럼명을 변수로 지정해 둡니다. 이후 코드에서 이 변수를 일관되게 사용합니다.
target_col = "next_arrive_time"

# 전처리 입력에 반드시 있어야 하는 필수 컬럼 목록입니다.
# 이 목록은 아래 prepare_features() 안에서 "누락된 컬럼이 없는지" 검사하는 데 사용됩니다.
# 실제 데이터 컬럼명이 다르면 df.columns 출력을 확인한 뒤 이 목록을 수정합니다.
required_cols = [
    "route_id",
    "vh_id",
    "route_nm",
    "now_latitude",
    "now_longitude",
    "now_station",
    "now_arrive_time",
    "distance",
    "next_station",
    "next_latitude",
    "next_longitude",
    "date"
]

In [12]:
def prepare_features(df_input):

    # 원본을 직접 수정하지 않도록 복사본을 만들어 작업합니다.
    # (함수 밖의 데이터가 의도치 않게 바뀌는 것을 막기 위함입니다.)
    data = df_input.copy()

    # 필수 컬럼이 빠지지 않았는지 먼저 검사합니다.
    # 누락된 컬럼이 있으면 어떤 컬럼이 없는지 알려 주는 오류를 발생시켜 원인을 빨리 찾게 합니다.
    missing_cols = [col for col in required_cols if col not in data.columns]
    if missing_cols:
        raise ValueError(f"필수 컬럼이 누락되었습니다: {missing_cols}")

    # date를 datetime(날짜형)으로 변환한 뒤, 모델이 활용하기 좋은 숫자 파생 컬럼을 만듭니다.
    data["date"] = pd.to_datetime(data["date"])
    data["year"] = data["date"].dt.year                  # 연도
    data["month"] = data["date"].dt.month                # 월
    data["day"] = data["date"].dt.day                    # 일
    data["dayofweek"] = data["date"].dt.dayofweek        # 요일 (월=0 ... 일=6)

    # now_arrive_time의 "06시" 같은 문자열에서 숫자 부분만 추출해 now_hour(정수 시간)로 만듭니다.
    # str.extract(r"(\d+)")는 문자열에서 연속된 숫자를 뽑아내는 처리입니다. ("06시" -> "06")
    data["now_hour"] = (
        data["now_arrive_time"].astype(str).str.extract(r"(\d+)").astype(float)
    )

    # 변환을 마친 원본 date, now_arrive_time 컬럼은 더 이상 필요 없으므로 feature에서 제외합니다.
    data = data.drop(columns=["date", "now_arrive_time"])

    # 정답(target) 컬럼이 들어 있으면 제거합니다. (입력 feature에는 정답이 포함되면 안 됩니다.)
    # 예측용 데이터에는 보통 target이 없으므로, 있을 때만 제거하도록 조건을 둡니다.
    if target_col in data.columns:
        data = data.drop(columns=[target_col])

    # 단순 식별 번호인 id 컬럼이 있으면 제거합니다. (예측에 도움이 되지 않는 정보입니다.)
    if "id" in data.columns:
        data = data.drop(columns=["id"])

    return data  # 정리된 feature DataFrame을 돌려줍니다.

In [13]:
df_model = df.copy()

X_preprocess = prepare_features(df_model)

In [14]:
X_preprocess

,route_id,vh_id,route_nm,now_latitude,now_longitude,now_station,distance,next_station,next_latitude,next_longitude,year,month,day,dayofweek,now_hour
0,405136001,7997025,360-1,33.456267,126.551750,제주대학교입구,266.0,제대마을,33.457724,126.554014,2019,10,15,1,6.0
1,405136001,7997025,360-1,33.457724,126.554014,제대마을,333.0,제대아파트,33.458783,126.557353,2019,10,15,1,6.0
2,405136001,7997025,360-1,33.458783,126.557353,제대아파트,415.0,제주대학교,33.459893,126.561624,2019,10,15,1,6.0
3,405136001,7997025,360-1,33.479705,126.543811,남국원(아라방면),578.0,제주여자중고등학교(아라방면),33.484860,126.542928,2019,10,15,1,6.0
4,405136001,7997025,360-1,33.485662,126.494923,도호동,374.0,은남동,33.485822,126.490897,2019,10,15,1,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210452,405328102,7983486,281-2,33.255783,126.577450,비석거리,528.0,삼아아파트,33.251896,126.574417,2019,10,28,0,21.0
210453,405328102,7983486,281-2,33.248595,126.568527,동문로터리,280.0,매일올레시장 7번입구,33.249753,126.565959,2019,10,28,0,21.0
210454,405328102,7983486,281-2,33.251891,126.560303,서귀포시 구 버스터미널,114.0,아랑조을거리 입구,33.251084,126.559551,2019,10,28,0,21.0
210455,405328102,7983486,281-2,33.251084,126.559551,아랑조을거리 입구,223.0,평생학습관,33.249504,126.558068,2019,10,28,0,21.0
210456,405328102,7983486,281-2,33.248487,126.511195,대륜동주민센터,189.0,서귀포버스터미널(가상정류소),33.249091,126.509224,2019,10,28,0,21.0

In [15]:
categorical_features = [
    "route_nm",
    "now_station",
    "next_station"
]

categorical_transformer = Pipeline(steps=[
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer(transformers=[
    ("cat", categorical_transformer, categorical_features)
], remainder = "passthrough")

In [16]:
X_cat_encoded = preprocessor.fit_transform(X_preprocess)

In [28]:
encoded_feature_names = preprocessor.get_feature_names_out()
encoded_feature_names

array(['cat__route_nm_201-11', 'cat__route_nm_201-12',
       'cat__route_nm_201-13', 'cat__route_nm_201-14',
       'cat__route_nm_201-15', 'cat__route_nm_201-16',
       'cat__route_nm_201-17', 'cat__route_nm_201-18',
       'cat__route_nm_201-21', 'cat__route_nm_201-22',
       'cat__route_nm_201-24', 'cat__route_nm_201-26',
       'cat__route_nm_201-27', 'cat__route_nm_281-1',
       'cat__route_nm_281-2', 'cat__route_nm_360-1',
       'cat__route_nm_360-12', 'cat__route_nm_360-2',
       'cat__route_nm_360-7', 'cat__route_nm_365-21',
       'cat__route_nm_365-22', 'cat__now_station_911의원',
       'cat__now_station_LH아파트', 'cat__now_station_가마초등학교',
       'cat__now_station_가흥동', 'cat__now_station_거로 입구',
       'cat__now_station_견월교', 'cat__now_station_계룡동',
       'cat__now_station_고도농원', 'cat__now_station_고래왓',
       'cat__now_station_고망난돌입구', 'cat__now_station_고산동산(광양방면)',
       'cat__now_station_고산동산(아라방면)', 'cat__now_station_고성리 구 성산농협',
       'cat__now_station_고성리 성산농협', 'cat__now_station_고성리제주은행',
       'cat__now_station_고성오일시장', 'cat__now_station_고으니모르 국립제주박물관',
       'cat__now_station_공업단지 입구', 'cat__now_station_공천포',
       'cat__now_station_관덕정', 'cat__now_station_광대왓',
       'cat__now_station_광양', 'cat__now_station_광양사거리',
       'cat__now_station_광지동', 'cat__now_station_광치기해변',
       'cat__now_station_교래입구', 'cat__now_station_구 터미널',
       'cat__now_station_구좌보건지소', 'cat__now_station_구좌중앙초등학교',
       'cat__now_station_국립제주박물관', 'cat__now_station_그린카센터',
       'cat__now_station_금붕사', 'cat__now_station_금산목',
       'cat__now_station_김녕리', 'cat__now_station_김녕해수욕장',
       'cat__now_station_김녕환승정류장(김녕초등학교)', 'cat__now_station_꽃동산',
       'cat__now_station_난산입구', 'cat__now_station_난산입구(성산기상대)',
       'cat__now_station_남국사', 'cat__now_station_남국원(광양방면)',
       'cat__now_station_남국원(아라방면)', 'cat__now_station_남녕고등학교',
       'cat__now_station_남서광마을', 'cat__now_station_남서광마을입구',
       'cat__now_station_남성마을입구', 'cat__now_station_남원1리사무소',
       'cat__now_station_남원생활체육관', 'cat__now_station_남원읍사무소',
       'cat__now_station_남원취락구조', 'cat__now_station_남원포구입구',
       'cat__now_station_남흘동', 'cat__now_station_노형오거리',
       'cat__now_station_노형초등학교', 'cat__now_station_농협 하나로마트',
       'cat__now_station_농협주유소', 'cat__now_station_다호마을',
       'cat__now_station_답다니', 'cat__now_station_대륜동주민센터',
       'cat__now_station_대림2차아파트', 'cat__now_station_대섬입구',
       'cat__now_station_대원상동', 'cat__now_station_대화동',
       'cat__now_station_도호동', 'cat__now_station_동광양',
       'cat__now_station_동문로터리', 'cat__now_station_동문성당',
       'cat__now_station_동복리', 'cat__now_station_동복리관광체험어장',
       'cat__now_station_동복리휴게소', 'cat__now_station_동부보건소',
       'cat__now_station_동산교', 'cat__now_station_동성동',
       'cat__now_station_동성마을', 'cat__now_station_동원산업',
       'cat__now_station_뒤통모루', 'cat__now_station_뒷빌레',
       'cat__now_station_롯데마트', 'cat__now_station_마방목지',
       'cat__now_station_만장굴입구', 'cat__now_station_망장포 입구',
       'cat__now_station_매일올레시장 7번입구', 'cat__now_station_맹살공원',
       'cat__now_station_명신마을', 'cat__now_station_무도동',
       'cat__now_station_문서교', 'cat__now_station_문예회관',
       'cat__now_station_법호촌 온성학교', 'cat__now_station_법호촌입구',
       'cat__now_station_보목입구', 'cat__now_station_보성시장',
       'cat__now_station_부영아파트', 'cat__now_station_북촌다려마을',
       'cat__now_station_북촌리', 'cat__now_station_북촌리해동',
       'cat__now_station_비석거리', 'cat__now_station_사라봉',
       'cat__now_station_사라봉오거리', 'cat__now_station_사회복지법인 춘강',
       'cat__now_station_산열이통입구', 'cat__now_station_산천단',
       'cat__now_station_산천단 한국폴리텍대학', 'cat__now_station_삼달교차로',
       'cat__now_station_삼매봉', 'cat__now_station_삼매봉입구',
       'cat__now_station_삼무공원사거리', 'cat__now_station_삼성여자고등학교',
       'cat__now_station_삼성초등학교', 'cat__now_station_삼아아파트',
       'cat__now_station_삼양2동', 'cat__now_station_삼양검문소',
       'cat__now_station_삼양동주민센터', 'cat__now_station_삼양초등학교',
       'cat__now_station_상도리 세화고등학교', 'cat__now_station_상도마을회관',
       'cat__now_station_상원동', 'cat__now_station_상효입구',
       'cat__now_station_샤인빌리조트입구', 'cat__now_station_서귀포동부도서관',
       'cat__now_station_서귀포버스터미널(가상정류소)', 'cat__now_station_서귀포산업과학고등학교',
       'cat__now_station_서귀포시 구 버스터미널', 'cat__now_station_서귀포여자고등학교',
       'cat__now_station_서문시장', 'cat__now_station_서성동',
       'cat__now_station_서소동', 'cat__now_station_성산고등학교',
       'cat__now_station_성산고입구삼거리', 'cat__now_station_성산국민체육센터',
       'cat__now_station_성산농협종합유통센터', 'cat__now_station_성산리',
       'cat__now_station_성산리 취락구조', 'cat__now_station_성산리입구',
       'cat__now_station_성산읍사무소', 'cat__now_station_성산일출봉입구',
       'cat__now_station_성산포 수협', 'cat__now_station_성산포수협표선지점',
       'cat__now_station_성산항입구', 'cat__now_station_성산환승정류장(고성리 한국물류)',
       'cat__now_station_성산환승정류장(고성리 회전교차로)', 'cat__now_station_성판악',
       'cat__now_station_세기아파트', 'cat__now_station_세천동',
       'cat__now_station_세화2리사무소', 'cat__now_station_세화고등학교',
       'cat__now_station_세화리구좌농협', 'cat__now_station_세화리시장2동',
       'cat__now_station_세화환승정류장(세화리)', 'cat__now_station_송천교',
       'cat__now_station_수농원', 'cat__now_station_수모루',
       'cat__now_station_수악교', 'cat__now_station_시민회관',
       'cat__now_station_시티주유소', 'cat__now_station_시흥리',
       'cat__now_station_시흥리사무소', 'cat__now_station_신례2리교차로',
       'cat__now_station_신산로', 'cat__now_station_신산리',
       'cat__now_station_신산환승정류장(성산농협신산지점)', 'cat__now_station_신성동',
       'cat__now_station_신양리입구', 'cat__now_station_신천리',
       'cat__now_station_신천리취락구조', 'cat__now_station_신촌리',
       'cat__now_station_신촌초등학교', 'cat__now_station_신풍리하동',
       'cat__now_station_신협', 'cat__now_station_신효',
       'cat__now_station_신효동', 'cat__now_station_신흥1번지',
       'cat__now_station_신흥교차로', 'cat__now_station_신흥리취락구조',
       'cat__now_station_씨사이드홈', 'cat__now_station_아라동주민센터',
       'cat__now_station_아라주공아파트', 'cat__now_station_아라초등학교',
       'cat__now_station_아랑조을거리 입구', 'cat__now_station_앞동산',
       'cat__now_station_양지(추모)공원', 'cat__now_station_어촌계입구',
       'cat__now_station_여 의 물', 'cat__now_station_연동대림1차아파트',
       'cat__now_station_연동입구', 'cat__now_station_연동주민센터',
       'cat__now_station_영등물', 'cat__now_station_영천동주민센터',
       'cat__now_station_오라3동', 'cat__now_station_오라오거리',
       'cat__now_station_오조리', 'cat__now_station_오조리 입구',
       'cat__now_station_오조리상동입구', 'cat__now_station_오조리하동',
       'cat__now_station_오조해녀의집', 'cat__now_station_오현중고등학교',
       'cat__now_station_오희준 공원', 'cat__now_station_온평리',
       'cat__now_station_온평초등학교', 'cat__now_station_용담1동주민센터',
       'cat__now_station_용문마을', 'cat__now_station_용문마을회관',
       'cat__now_station_용문사거리', 'cat__now_station_용천마을',
       'cat__now_station_우당도서관', 'cat__now_station_웃 인다 마을',
       'cat__now_station_원노형', 'cat__now_station_원당봉',
       'cat__now_station_원당분화원', 'cat__now_station_월구마을',
       'cat__now_station_월라봉', 'cat__now_station_월랑마을 남녕고등학교',
       'cat__now_station_월성 마을', 'cat__now_station_월정리',
       'cat__now_station_월정리 용천동', 'cat__now_station_위미1리사무소',
       'cat__now_station_위미3리', 'cat__now_station_위미3리 마을회관',
       'cat__now_station_위미문화의집', 'cat__now_station_위미초등학교',
       'cat__now_station_으뜸마을', 'cat__now_station_은남동',
       'cat__now_station_인다마을', 'cat__now_station_인화초등학교',
       'cat__now_station_입석동', 'cat__now_station_전경대 입구',
       'cat__now_station_정존마을', 'cat__now_station_제대마을',
       'cat__now_station_제대아파트', 'cat__now_station_제원아파트',
       'cat__now_station_제일교 동문시장입구', 'cat__now_station_제주고등학교/중흥S클래스',
       'cat__now_station_제주국제공항(구제주방면)', 'cat__now_station_제주국제공항(신제주방면)',
       'cat__now_station_제주국제대학교', 'cat__now_station_제주대학교',
       'cat__now_station_제주대학교 입구', 'cat__now_station_제주대학교교육대학',
       'cat__now_station_제주대학교병원', 'cat__now_station_제주대학교입구',
       'cat__now_station_제주도청 신제주로터리', 'cat__now_station_제주동중학교',
       'cat__now_station_제주버스터미널', 'cat__now_station_제주버스터미널(가상정류소)',
       'cat__now_station_제주시청(광양방면)', 'cat__now_station_제주시청(아라방면)',
       'cat__now_station_제주여자상업고등학교', 'cat__now_station_제주여자중고등학교(광양방면)',
       'cat__now_station_제주여자중고등학교(아라방면)', 'cat__now_station_제주의료원',
       'cat__now_station_제주제일고등학교', 'cat__now_station_제주중앙여자고등학교(광양방면)',
       'cat__now_station_제주중앙여자고등학교(아라방면)', 'cat__now_station_제주중학교/제주향교',
       'cat__now_station_제주지방법원(광양방면)', 'cat__now_station_제주지방법원(아라방면)',
       'cat__now_station_제주컨트리클럽', 'cat__now_station_제주한라대학교',
       'cat__now_station_조천리', 'cat__now_station_조천만세동산',
       'cat__now_station_조천읍사무소', 'cat__now_station_조천체육관',
       'cat__now_station_조천초등학교', 'cat__now_station_조천환승정류장(조천리사무소)',
       'cat__now_station_조천환승정류장(조천우체국)', 'cat__now_station_종달리',
       'cat__now_station_종달초등학교', 'cat__now_station_종보존연구센터',
       'cat__now_station_종합사격장', 'cat__now_station_주공 3 4단지',
       'cat__now_station_주암주택', 'cat__now_station_죽성마을 입구',
       'cat__now_station_중앙로(국민은행)', 'cat__now_station_중앙로(현대약국)',
       'cat__now_station_중앙로터리', 'cat__now_station_중흥S클래스아파트',
       'cat__now_station_지경곰', 'cat__now_station_진드르',
       'cat__now_station_진은동', 'cat__now_station_창남거리',
       'cat__now_station_천수동', 'cat__now_station_청소년문화의집',
       'cat__now_station_충혼묘지', 'cat__now_station_케이티앤지',
       'cat__now_station_탐라도서관', 'cat__now_station_탐라장애인 종합복지관',
       'cat__now_station_태흥3리', 'cat__now_station_태흥3리사무소',
       'cat__now_station_태흥초등학교', 'cat__now_station_토산관광지구입구',
       'cat__now_station_토평 보목입구', 'cat__now_station_토평마을회관',
       'cat__now_station_평대리동동', 'cat__now_station_평대리사무소',
       'cat__now_station_평대리서동', 'cat__now_station_평대초등학교',
       'cat__now_station_평생학습관', 'cat__now_station_평안전문요양원',
       'cat__now_station_폭낭사거리', 'cat__now_station_표선오일시장',
       'cat__now_station_표선초등학교', 'cat__now_station_표선파출소',
       'cat__now_station_표선환승정류장(표선리 제주은행)',
       'cat__now_station_표선환승정류장(표선리사무소)', 'cat__now_station_하도리',
       'cat__now_station_하도리 개긋물', 'cat__now_station_하도리 서문동',
       'cat__now_station_하도리동동', 'cat__now_station_하도리면수동',
       'cat__now_station_하도리창흥동', 'cat__now_station_하도초등학교',
       'cat__now_station_하례1리입구', 'cat__now_station_하례환승정류장(하례리입구)',
       'cat__now_station_하천리취락구조', 'cat__now_station_하천하동',
       'cat__now_station_한국병원', 'cat__now_station_한동리',
       'cat__now_station_한동리서동', 'cat__now_station_한라병원',
       'cat__now_station_한라산 둘레길', 'cat__now_station_한라생태숲',
       'cat__now_station_한라중학교/부영아파트', 'cat__now_station_한지교차로',
       'cat__now_station_한지동', 'cat__now_station_함덕농협지소',
       'cat__now_station_함덕리 3구', 'cat__now_station_함덕리 4구',
       'cat__now_station_함덕리(4구)', 'cat__now_station_함덕비석거리',
       'cat__now_station_함덕환승정류장(함덕해수욕장)', 'cat__now_station_해녀박물관입구',
       'cat__now_station_해양연구소', 'cat__now_station_행원농공단지',
       'cat__now_station_행원리', 'cat__now_station_현대산부인과',
       'cat__now_station_혼인지입구', 'cat__now_station_홍랑로입구',
       'cat__now_station_화물청사입구', 'cat__now_station_화북남문',
       'cat__now_station_화북주공아파트', 'cat__now_station_화북초등학교',
       'cat__now_station_화성농장', 'cat__now_station_효돈농협하나로마트',
       'cat__now_station_효돈중학교', 'cat__now_station_효돈초등학교',
       'cat__now_station_효돈축구공원', 'cat__now_station_효례교',
       'cat__now_station_흙통', 'cat__now_station_희진주유소',
       'cat__next_station_911의원', 'cat__next_station_LH아파트',
       'cat__next_station_가마초등학교', 'cat__next_station_가흥동',
       'cat__next_station_거로 입구', 'cat__next_station_견월교',
       'cat__next_station_계룡동', 'cat__next_station_고도농원',
       'cat__next_station_고래왓', 'cat__next_station_고망난돌입구',
       'cat__next_station_고산동산(광양방면)', 'cat__next_station_고산동산(아라방면)',
       'cat__next_station_고성리 구 성산농협', 'cat__next_station_고성리 성산농협',
       'cat__next_station_고성리제주은행', 'cat__next_station_고성오일시장',
       'cat__next_station_고으니모르 국립제주박물관', 'cat__next_station_공업단지 입구',
       'cat__next_station_공천포', 'cat__next_station_관덕정',
       'cat__next_station_광대왓', 'cat__next_station_광양',
       'cat__next_station_광양사거리', 'cat__next_station_광지동',
       'cat__next_station_광치기해변', 'cat__next_station_교래입구',
       'cat__next_station_구 터미널', 'cat__next_station_구좌보건지소',
       'cat__next_station_구좌중앙초등학교', 'cat__next_station_국립제주박물관',
       'cat__next_station_그린카센터', 'cat__next_station_금붕사',
       'cat__next_station_금산목', 'cat__next_station_김녕리',
       'cat__next_station_김녕해수욕장', 'cat__next_station_김녕환승정류장(김녕초등학교)',
       'cat__next_station_꽃동산', 'cat__next_station_난산입구',
       'cat__next_station_난산입구(성산기상대)', 'cat__next_station_남국사',
       'cat__next_station_남국원(광양방면)', 'cat__next_station_남국원(아라방면)',
       'cat__next_station_남녕고등학교', 'cat__next_station_남서광마을',
       'cat__next_station_남서광마을입구', 'cat__next_station_남성마을입구',
       'cat__next_station_남원1리사무소', 'cat__next_station_남원생활체육관',
       'cat__next_station_남원읍사무소', 'cat__next_station_남원취락구조',
       'cat__next_station_남원포구입구', 'cat__next_station_남흘동',
       'cat__next_station_노형오거리', 'cat__next_station_노형초등학교',
       'cat__next_station_농협 하나로마트', 'cat__next_station_농협주유소',
       'cat__next_station_다호마을', 'cat__next_station_답다니',
       'cat__next_station_대륜동주민센터', 'cat__next_station_대림2차아파트',
       'cat__next_station_대섬입구', 'cat__next_station_대원상동',
       'cat__next_station_대화동', 'cat__next_station_도호동',
       'cat__next_station_동광양', 'cat__next_station_동문로터리',
       'cat__next_station_동문성당', 'cat__next_station_동복리',
       'cat__next_station_동복리관광체험어장', 'cat__next_station_동복리휴게소',
       'cat__next_station_동부보건소', 'cat__next_station_동산교',
       'cat__next_station_동성동', 'cat__next_station_동성마을',
       'cat__next_station_동원산업', 'cat__next_station_뒤통모루',
       'cat__next_station_뒷빌레', 'cat__next_station_롯데마트',
       'cat__next_station_마방목지', 'cat__next_station_만장굴입구',
       'cat__next_station_망장포 입구', 'cat__next_station_매일올레시장 7번입구',
       'cat__next_station_맹살공원', 'cat__next_station_명신마을',
       'cat__next_station_무도동', 'cat__next_station_문서교',
       'cat__next_station_문예회관', 'cat__next_station_법호촌 온성학교',
       'cat__next_station_법호촌입구', 'cat__next_station_보목입구',
       'cat__next_station_보성시장', 'cat__next_station_부영아파트',
       'cat__next_station_북촌다려마을', 'cat__next_station_북촌리',
       'cat__next_station_북촌리해동', 'cat__next_station_비석거리',
       'cat__next_station_사라봉', 'cat__next_station_사라봉오거리',
       'cat__next_station_사회복지법인 춘강', 'cat__next_station_산열이통입구',
       'cat__next_station_산천단', 'cat__next_station_산천단 한국폴리텍대학',
       'cat__next_station_삼달교차로', 'cat__next_station_삼매봉',
       'cat__next_station_삼매봉입구', 'cat__next_station_삼무공원사거리',
       'cat__next_station_삼성여자고등학교', 'cat__next_station_삼성초등학교',
       'cat__next_station_삼아아파트', 'cat__next_station_삼양2동',
       'cat__next_station_삼양검문소', 'cat__next_station_삼양동주민센터',
       'cat__next_station_삼양초등학교', 'cat__next_station_상도리 세화고등학교',
       'cat__next_station_상도마을회관', 'cat__next_station_상원동',
       'cat__next_station_상효입구', 'cat__next_station_샤인빌리조트입구',
       'cat__next_station_서귀포동부도서관', 'cat__next_station_서귀포버스터미널',
       'cat__next_station_서귀포버스터미널(가상정류소)',
       'cat__next_station_서귀포산업과학고등학교', 'cat__next_station_서귀포시 구 버스터미널',
       'cat__next_station_서귀포여자고등학교', 'cat__next_station_서문시장',
       'cat__next_station_서성동', 'cat__next_station_서소동',
       'cat__next_station_성산고등학교', 'cat__next_station_성산고입구삼거리',
       'cat__next_station_성산국민체육센터', 'cat__next_station_성산농협종합유통센터',
       'cat__next_station_성산리', 'cat__next_station_성산리 취락구조',
       'cat__next_station_성산리입구', 'cat__next_station_성산읍사무소',
       'cat__next_station_성산일출봉입구', 'cat__next_station_성산포 수협',
       'cat__next_station_성산포수협표선지점', 'cat__next_station_성산항입구',
       'cat__next_station_성산환승정류장(고성리 한국물류)',
       'cat__next_station_성산환승정류장(고성리 회전교차로)', 'cat__next_station_성판악',
       'cat__next_station_세기아파트', 'cat__next_station_세천동',
       'cat__next_station_세화2리사무소', 'cat__next_station_세화고등학교',
       'cat__next_station_세화리구좌농협', 'cat__next_station_세화리시장2동',
       'cat__next_station_세화환승정류장(세화리)', 'cat__next_station_송천교',
       'cat__next_station_수농원', 'cat__next_station_수모루',
       'cat__next_station_수악교', 'cat__next_station_시민회관',
       'cat__next_station_시티주유소', 'cat__next_station_시흥리',
       'cat__next_station_시흥리사무소', 'cat__next_station_신례2리교차로',
       'cat__next_station_신산로', 'cat__next_station_신산리',
       'cat__next_station_신산환승정류장(성산농협신산지점)', 'cat__next_station_신성동',
       'cat__next_station_신양리입구', 'cat__next_station_신천리',
       'cat__next_station_신천리취락구조', 'cat__next_station_신촌리',
       'cat__next_station_신촌초등학교', 'cat__next_station_신풍리하동',
       'cat__next_station_신협', 'cat__next_station_신효',
       'cat__next_station_신효동', 'cat__next_station_신흥1번지',
       'cat__next_station_신흥교차로', 'cat__next_station_신흥리취락구조',
       'cat__next_station_씨사이드홈', 'cat__next_station_아라동주민센터',
       'cat__next_station_아라주공아파트', 'cat__next_station_아라초등학교',
       'cat__next_station_아랑조을거리 입구', 'cat__next_station_앞동산',
       'cat__next_station_양지(추모)공원', 'cat__next_station_어촌계입구',
       'cat__next_station_여 의 물', 'cat__next_station_연동대림1차아파트',
       'cat__next_station_연동입구', 'cat__next_station_연동주민센터',
       'cat__next_station_영등물', 'cat__next_station_영천동주민센터',
       'cat__next_station_오라3동', 'cat__next_station_오라오거리',
       'cat__next_station_오조리', 'cat__next_station_오조리 입구',
       'cat__next_station_오조리상동입구', 'cat__next_station_오조리하동',
       'cat__next_station_오조해녀의집', 'cat__next_station_오현중고등학교',
       'cat__next_station_오희준 공원', 'cat__next_station_온평리',
       'cat__next_station_온평초등학교', 'cat__next_station_용담1동주민센터',
       'cat__next_station_용문마을', 'cat__next_station_용문마을회관',
       'cat__next_station_용문사거리', 'cat__next_station_용천마을',
       'cat__next_station_우당도서관', 'cat__next_station_웃 인다 마을',
       'cat__next_station_원노형', 'cat__next_station_원당봉',
       'cat__next_station_원당분화원', 'cat__next_station_월구마을',
       'cat__next_station_월라봉', 'cat__next_station_월랑마을 남녕고등학교',
       'cat__next_station_월성 마을', 'cat__next_station_월정리',
       'cat__next_station_월정리 용천동', 'cat__next_station_위미1리사무소',
       'cat__next_station_위미3리', 'cat__next_station_위미3리 마을회관',
       'cat__next_station_위미문화의집', 'cat__next_station_위미초등학교',
       'cat__next_station_으뜸마을', 'cat__next_station_은남동',
       'cat__next_station_인다마을', 'cat__next_station_인화초등학교',
       'cat__next_station_입석동', 'cat__next_station_전경대 입구',
       'cat__next_station_정존마을', 'cat__next_station_제대마을',
       'cat__next_station_제대아파트', 'cat__next_station_제원아파트',
       'cat__next_station_제일교 동문시장입구', 'cat__next_station_제주고등학교/중흥S클래스',
       'cat__next_station_제주국제공항(구제주방면)',
       'cat__next_station_제주국제공항(신제주방면)', 'cat__next_station_제주국제대학교',
       'cat__next_station_제주대학교', 'cat__next_station_제주대학교 입구',
       'cat__next_station_제주대학교교육대학', 'cat__next_station_제주대학교병원',
       'cat__next_station_제주대학교입구', 'cat__next_station_제주도청 신제주로터리',
       'cat__next_station_제주동중학교', 'cat__next_station_제주버스터미널',
       'cat__next_station_제주버스터미널(가상정류소)',
       'cat__next_station_제주버스터미널(종점)', 'cat__next_station_제주시청(광양방면)',
       'cat__next_station_제주시청(아라방면)', 'cat__next_station_제주여자상업고등학교',
       'cat__next_station_제주여자중고등학교(광양방면)',
       'cat__next_station_제주여자중고등학교(아라방면)', 'cat__next_station_제주의료원',
       'cat__next_station_제주제일고등학교', 'cat__next_station_제주중앙여자고등학교(광양방면)',
       'cat__next_station_제주중앙여자고등학교(아라방면)',
       'cat__next_station_제주중학교/제주향교', 'cat__next_station_제주지방법원(광양방면)',
       'cat__next_station_제주지방법원(아라방면)', 'cat__next_station_제주컨트리클럽',
       'cat__next_station_제주한라대학교', 'cat__next_station_제주한라대학교(종점)',
       'cat__next_station_조천리', 'cat__next_station_조천만세동산',
       'cat__next_station_조천읍사무소', 'cat__next_station_조천체육관',
       'cat__next_station_조천초등학교', 'cat__next_station_조천환승정류장(조천리사무소)',
       'cat__next_station_조천환승정류장(조천우체국)', 'cat__next_station_종달리',
       'cat__next_station_종달초등학교', 'cat__next_station_종보존연구센터',
       'cat__next_station_종합사격장', 'cat__next_station_주공 3 4단지',
       'cat__next_station_주암주택', 'cat__next_station_죽성마을 입구',

In [18]:
X_cat_encoded_df = pd.DataFrame(
    X_cat_encoded.toarray(),
    columns = encoded_feature_names
)

In [19]:
X_cat_encoded_df

,cat__route_nm_201-11,cat__route_nm_201-12,cat__route_nm_201-13,cat__route_nm_201-14,cat__route_nm_201-15,cat__route_nm_201-16,cat__route_nm_201-17,cat__route_nm_201-18,cat__route_nm_201-21,cat__route_nm_201-22,...,remainder__now_latitude,remainder__now_longitude,remainder__distance,remainder__next_latitude,remainder__next_longitude,remainder__year,remainder__month,remainder__day,remainder__dayofweek,remainder__now_hour
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,33.456267,126.551750,266.0,33.457724,126.554014,2019.0,10.0,15.0,1.0,6.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,33.457724,126.554014,333.0,33.458783,126.557353,2019.0,10.0,15.0,1.0,6.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,33.458783,126.557353,415.0,33.459893,126.561624,2019.0,10.0,15.0,1.0,6.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,33.479705,126.543811,578.0,33.484860,126.542928,2019.0,10.0,15.0,1.0,6.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,33.485662,126.494923,374.0,33.485822,126.490897,2019.0,10.0,15.0,1.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210452,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,33.255783,126.577450,528.0,33.251896,126.574417,2019.0,10.0,28.0,0.0,21.0
210453,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,33.248595,126.568527,280.0,33.249753,126.565959,2019.0,10.0,28.0,0.0,21.0
210454,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,33.251891,126.560303,114.0,33.251084,126.559551,2019.0,10.0,28.0,0.0,21.0
210455,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,33.251084,126.559551,223.0,33.249504,126.558068,2019.0,10.0,28.0,0.0,21.0
210456,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,33.248487,126.511195,189.0,33.249091,126.509224,2019.0,10.0,28.0,0.0,21.0

In [20]:
y = df_model[target_col]

y

0         24
1         36
2         40
3         42
4         64
          ..
210452    96
210453    50
210454    16
210455    38
210456    24
Name: next_arrive_time, Length: 210457, dtype: int64

In [21]:
new_required_cols = [
    "route_id",
    "vh_id",
    "route_nm",
    "now_latitude",
    "now_longitude",
    "now_station",
    "distance",
    "next_station",
    "next_latitude",
    "next_longitude",
    "year",
    "month",
    "day",
    "dayofweek",
    "now_hour"
]

In [22]:
X = X_preprocess[new_required_cols]
X

,route_id,vh_id,route_nm,now_latitude,now_longitude,now_station,distance,next_station,next_latitude,next_longitude,year,month,day,dayofweek,now_hour
0,405136001,7997025,360-1,33.456267,126.551750,제주대학교입구,266.0,제대마을,33.457724,126.554014,2019,10,15,1,6.0
1,405136001,7997025,360-1,33.457724,126.554014,제대마을,333.0,제대아파트,33.458783,126.557353,2019,10,15,1,6.0
2,405136001,7997025,360-1,33.458783,126.557353,제대아파트,415.0,제주대학교,33.459893,126.561624,2019,10,15,1,6.0
3,405136001,7997025,360-1,33.479705,126.543811,남국원(아라방면),578.0,제주여자중고등학교(아라방면),33.484860,126.542928,2019,10,15,1,6.0
4,405136001,7997025,360-1,33.485662,126.494923,도호동,374.0,은남동,33.485822,126.490897,2019,10,15,1,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210452,405328102,7983486,281-2,33.255783,126.577450,비석거리,528.0,삼아아파트,33.251896,126.574417,2019,10,28,0,21.0
210453,405328102,7983486,281-2,33.248595,126.568527,동문로터리,280.0,매일올레시장 7번입구,33.249753,126.565959,2019,10,28,0,21.0
210454,405328102,7983486,281-2,33.251891,126.560303,서귀포시 구 버스터미널,114.0,아랑조을거리 입구,33.251084,126.559551,2019,10,28,0,21.0
210455,405328102,7983486,281-2,33.251084,126.559551,아랑조을거리 입구,223.0,평생학습관,33.249504,126.558068,2019,10,28,0,21.0
210456,405328102,7983486,281-2,33.248487,126.511195,대륜동주민센터,189.0,서귀포버스터미널(가상정류소),33.249091,126.509224,2019,10,28,0,21.0

In [23]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

X_train.shape, X_test.shape

((168365, 15), (42092, 15))

In [24]:
xgb_model = XGBRegressor()

model_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", xgb_model)
])

_ = model_pipeline.fit(X_train, y_train)

print("모델 학습 완료")

모델 학습 완료

In [25]:
y_pred = model_pipeline.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)

print(f"MAE: {mae:.4f}")

MAE: 23.0865

In [26]:
# 예측할 새로운 데이터
new_data = pd.DataFrame([
    {
        "date": "2019-10-21",
        "route_id": 405136001,
        "vh_id": 7997025,
        "route_nm": "360-1",
        "now_latitude": 33.456267,
        "now_longitude": 126.551750,
        "now_station": "제주대학교입구",
        "now_arrive_time": "08시",
        "distance": 300.0,
        "next_station": "제대마을",
        "next_latitude": 33.457724,
        "next_longitude": 126.554014
    }
])

new_data

,date,route_id,vh_id,route_nm,now_latitude,now_longitude,now_station,now_arrive_time,distance,next_station,next_latitude,next_longitude
0,2019-10-21,405136001,7997025,360-1,33.456267,126.55175,제주대학교입구,08시,300.0,제대마을,33.457724,126.554014

In [27]:
new_data_prepared = prepare_features(new_data)

new_pred = model_pipeline.predict(new_data_prepared)

result_df = new_data.copy()
result_df["predicted_next_arrive_time"] = new_pred
result_df["predicted_next_arrive_time"] = result_df["predicted_next_arrive_time"].round(2)

result_df[[
    "route_nm",
    "now_station",
    "next_station",
    "now_arrive_time",
    "distance",
    "predicted_next_arrive_time"
]]

,route_nm,now_station,next_station,now_arrive_time,distance,predicted_next_arrive_time
0,360-1,제주대학교입구,제대마을,08시,300.0,37.27